import type { BrokerInvoice } from './broker-invoices'
import { formatAed, invoiceDealLabel } from './broker-invoices'

/**
 * Generate a printable invoice document (browser Print → Save as PDF).
 * No PDF library in the stack — matches the project's lightweight download patterns.
 */
export function openBrokerInvoicePrintView(invoice: BrokerInvoice): void {
  const brokerName = invoice.agents?.full_name || 'Broker'
  const company = invoice.agents?.company_name || 'Gnanova Real Estate'
  const property = invoiceDealLabel(invoice)
  const client = invoice.deals?.client_name || '—'
  const due = invoice.due_date || '—'
  const paid = Number(invoice.amount_paid || 0)
  const amount = Number(invoice.amount || 0)
  const balance = Math.max(0, amount - paid)

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>${invoice.invoice_number}</title>
  <style>
    body { font-family: Georgia, 'Times New Roman', serif; color: #0f172a; margin: 40px; }
    h1 { font-size: 22px; margin: 0 0 4px; }
    .muted { color: #64748b; font-size: 13px; }
    table { width: 100%; border-collapse: collapse; margin-top: 28px; }
    th, td { text-align: left; padding: 10px 8px; border-bottom: 1px solid #e2e8f0; font-size: 14px; }
    th { color: #64748b; font-weight: 600; font-size: 12px; text-transform: uppercase; letter-spacing: 0.04em; }
    .totals { margin-top: 24px; max-width: 280px; margin-left: auto; }
    .totals div { display: flex; justify-content: space-between; padding: 6px 0; font-size: 14px; }
    .totals .grand { font-weight: 700; font-size: 16px; border-top: 2px solid #0f172a; margin-top: 8px; padding-top: 10px; }
    .badge { display: inline-block; padding: 2px 8px; border-radius: 4px; background: #f1f5f9; font-size: 12px; }
    @media print { button { display: none !important; } body { margin: 20px; } }
  </style>
</head>
<body>
  <button onclick="window.print()" style="padding:8px 14px;margin-bottom:20px;cursor:pointer;">Print / Save as PDF</button>
  <h1>Broker Commission Invoice</h1>
  <p class="muted">${company}</p>
  <p style="margin-top:20px"><strong>Invoice #</strong> ${invoice.invoice_number}<br/>
  <span class="badge">${invoice.status}${invoice.emi_plan ? ' · EMI' : ''}</span></p>
  <p><strong>Bill to:</strong> ${brokerName}<br/>
  <span class="muted">${invoice.agents?.email || ''}</span></p>
  <p><strong>Due date:</strong> ${due}</p>
  <table>
    <thead>
      <tr><th>Description</th><th>Client</th><th>Amount</th></tr>
    </thead>
    <tbody>
      <tr>
        <td>Commission — ${property}</td>
        <td>${client}</td>
        <td>${formatAed(amount)}</td>
      </tr>
    </tbody>
  </table>
  <div class="totals">
    <div><span>Amount</span><span>${formatAed(amount)}</span></div>
    <div><span>Paid</span><span>${formatAed(paid)}</span></div>
    <div class="grand"><span>Balance</span><span>${formatAed(balance)}</span></div>
  </div>
  <p class="muted" style="margin-top:40px">Generated by Gnanova · Invoice ID ${invoice.id}</p>
</body>
</html>`

  const w = window.open('', '_blank', 'noopener,noreferrer,width=800,height=900')
  if (!w) {
    alert('Pop-up blocked. Allow pop-ups to generate the invoice PDF.')
    return
  }
  w.document.write(html)
  w.document.close()
}
